# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "ubuntu:21.04"
    d.has_ssh = true
    d.remains_running = true
    # 使用容器内的命令来保持运行
    d.cmd = ["/bin/bash", "-c", "while true; do sleep 1000; done"]
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 1234, host_ip: "127.0.0.1"

  # 配置 shell 脚本以在 Docker 容器中运行
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -qqy python3 python3-pip
    pip3 install flask sqlalchemy psycopg2-binary
  SHELL
end
